home/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='home'),
]

profiles/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.profile, name='profile'),
    path('edit/', views.edit_profile, name='edit_profile'),
    path('delete/', views.delete_account, name='delete_account'),
    path('purchases/', views.purchases, name='purchases'),
    path(
        'purchases_history/<order_number>/',
        views.purchases_history, name='purchases_history'),
]

toptech/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views
from .views import handler404, handler500, privacy_policy


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('products/', include('products.urls')),
    path('about/', include('about.urls')),
    path('basket/', include('basket.urls')),
    path('checkout/', include('checkout.urls')),
    path('profile/', include('profiles.urls')),
    path('contact/', include('contact.urls')),
    path('reviews/', include('reviews.urls')),
    path('privacy_policy/', views.privacy_policy, name='privacy_policy'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = 'toptech.views.handler404'
handler500 = 'toptech.views.handler500'

profiles/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from products.models import BRANDS, OS
from django_countries.fields import CountryField


class UserProfile(models.Model):
    """
    User Profile, so user can maintain profile,
    delete account, delivery information and order history
    """
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(null=True, blank=True, upload_to='profiles/',
                              default='default_images/default_profile.png')
    bio = models.TextField(verbose_name='Biography', null=True, blank=True)
    fav_brand = models.CharField(verbose_name='Favourite Brand',
                                 max_length=30, choices=BRANDS,
                                 null=True, blank=True, default='')
    fav_os = models.CharField(verbose_name='Favourite Operating System',
                              max_length=30, choices=OS, null=True,
                              blank=True, default='')
    default_phone_number = models.CharField(verbose_name='Phone Number',
                                            max_length=20, null=True,
                                            blank=True)
    default_country = CountryField(verbose_name='Country',
                                   blank_label='Select Country',
                                   null=True, blank=True)
    default_postcode = models.CharField(verbose_name='Postal Code',
                                        max_length=20, null=True,
                                        blank=True)
    default_town_or_city = models.CharField(verbose_name='Town or City',
                                            max_length=40, null=True,
                                            blank=True)
    default_street_address1 = models.CharField(verbose_name='Street Address',
                                               max_length=80, null=True,
                                               blank=True)
    default_street_address2 = models.CharField(verbose_name='Street\
                                               Address 2',
                                               max_length=80, null=True,
                                               blank=True)
    default_county = models.CharField(verbose_name='County',
                                      max_length=40, null=True,
                                      blank=True)

    def __str__(self):
        return self.user.username


@receiver(post_save, sender=User)
def create_or_update_user_profile(sender, instance, created, **kwargs):
    """
    Create/Update User profile
    """
    if created:
        UserProfile.objects.create(user=instance)
    instance.userprofile.save()

profiles/forms.py
from django import forms
from .widgets import CustomClearableFileInput
from .models import UserProfile


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('bio', 'fav_brand', 'fav_os',
                  'default_phone_number', 'default_street_address1',
                  'default_street_address2', 'default_town_or_city',
                  'default_postcode', 'default_country',
                  'default_county', 'image',)

    image = forms.ImageField(
        label='Image', required=False, widget=CustomClearableFileInput)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'border-black rounded'

profiles/views.py
from django.shortcuts import render, reverse, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from .models import UserProfile
from .forms import UserProfileForm
from django.contrib import messages
from checkout.models import Order


@login_required
def profile(request):
    """
    To render the profile page
    """

    profile = get_object_or_404(UserProfile, user=request.user)
    template = 'profiles/profile.html'
    context = {
        'profile': profile,
    }

    return render(request, template, context)


@login_required
def edit_profile(request):
    """
    To render the edit profile form page
    """

    profile = get_object_or_404(UserProfile, user=request.user)

    if request.method == 'POST':
        form = UserProfileForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            form.save()
            messages.success(
                request, 'Your profile has been updated')
            return redirect(reverse('profile'))
        else:
            messages.error(
                request, 'Update failed.\
                 Please make sure that the form is valid.')
    else:
        form = UserProfileForm(instance=profile)

    template = 'profiles/edit_profile.html'
    context = {
        'form': form,
        'profile': profile,
    }

    return render(request, template, context)


@login_required
def delete_account(request):
    """
    Delete account template
    """

    profile = User.objects.get(username=request.user)

    if request.method == 'POST':
        profile.delete()
        messages.success(request, 'Your account has been deleted!')
        return redirect(reverse('home'))

    template = 'profiles/delete_account.html'

    return render(request, template)


@login_required
def purchases(request):
    """
    To render all orders template page
    """

    profile = get_object_or_404(UserProfile, user=request.user)
    orders = profile.orders.all()

    template = 'profiles/purchases.html'
    context = {
        'profile': profile,
        'orders': orders,
    }

    return render(request, template, context)


@login_required
def purchases_history(request, order_number):
    order = get_object_or_404(Order, order_number=order_number)
    messages.info(request, (
        f'This is a past confirmation for order number {order_number}. '
        'A confirmation has been sent to your email'
    ))

    template = 'checkout/checkout_success.html'

    context = {
        'order': order,
        'from_profile': True,
    }

    return render(request, template, context)

profiles/templates/profiles/delete_account.html
{% extends "base.html" %}
{% load static %}

{% block head_title %}- Delete account{% endblock %}

{% if request.user == profile.user %}
{% block page_header %}
<div class="container header-container">
    <div class="row">
        <div class="col"></div>
    </div>
</div>
{% endblock %}

{% block content %}
<!--          Delete account container          -->
<div class="container">
    <div class="row">
        <div class="col-12 col-md-10 col-lg-8 offset-lg-2 offset-md-1 mt-3 mb-3">

            <!--          Title and sub title          -->
            <hr>
            <h1 class="logo-font text-center font-weight-bold" style="font-size: 30px;">Delete Account</h1>
            <hr>
        </div>
    </div>
    <div class="row">
        <div class="card col-12 col-md-10 col-lg-8 offset-md-1 offset-lg-2 mt-3 mb-3">
            <div class="row mx-0">
                <div class="col-12 col-md-10 offset-md-1 mt-3 mb-3">

                    <!--          Delete account form          -->
                    <form method="POST" class="form mb-3">
                        {% csrf_token %}
                        <h2 class="text-center my-5" style="font-size: 18px;">Are you sure that you want to delete your
                            account?</h2>
                        <div class="text-center">
                            <button class="btn btn-outline-danger font-weight-bold rounded mx-3 mb-3">Delete
                                account</button>
                            <a href="{% url 'profile' %}"
                                class="btn cancel-button font-weight-bold mx-3 mb-3">Cancel</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% endif %}

profiles/templates/profiles/edit_profile.html
{% extends "base.html" %}
{% load static %}

{% block head_title %}- Edit {{ profile.user.username }}'s profile{% endblock %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/profile.css' %}">
{% endblock %}

{% if request.user == profile.user %}
{% block page_header %}
<div class="container header-container">
    <div class="row">
        <div class="col"></div>
    </div>
</div>
{% endblock %}

{% block content %}

<!--          Edit Profile form container          -->
<div class="container">
    <div class="row">
        <div class="col-12 col-md-10 col-lg-8 offset-lg-2 offset-md-1 mt-3 mb-3">

            <!--          Title          -->
            <hr>
            <h1 class="logo-font text-center font-weight-bold" style="font-size: 30px;">{{ profile.user.username }}'s
                profile</h1>
            <hr>
        </div>
    </div>
    <div class="row">
        <div class="card col-12 col-md-10 col-lg-8 offset-md-1 offset-lg-2 mt-3 mb-3">
            <div class="row mx-0">
                <div class="col-12 col-md-10 offset-md-1 mt-3 mb-3">
                    <h2 class="mb-5 font-weight-bold" style="font-size: 24px;">Edit profile</h2>

                    <!--          Edit Profile form          -->
                    <form method="POST" action="{% url 'edit_profile' %}" class="form mb-3"
                        enctype="multipart/form-data">
                        {% csrf_token %}
                        {% for field in form %}
                        {% if field.name != 'image' %}
                        {{ field | as_crispy_field }}
                        {% else %}
                        {{ field }}
                        {% endif %}
                        {% endfor %}
                        <div class="text-center mt-5">
                            <button class="btn main-button font-weight-bold rounded mx-3 mb-3">Update Profile</button>
                            <a href="{% url 'profile' %}"
                                class="btn cancel-button font-weight-bold mx-3 mb-3">Cancel</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% endif %}

{% block postloadjs %}

<!--          JS file          -->
<script src="{% static 'js/profile_country_field.js' %}"></script>
{% endblock %}

profiles/templates/profiles/profile.html
{% extends "base.html" %}
{% load static %}

{% block head_title %}- {{ profile.user.username }}'s profile{% endblock %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/profile.css' %}">
{% endblock %}

{% block page_header %}
<div class="container header-container">
    <div class="row">
        <div class="col"></div>
    </div>
</div>
{% endblock %}

{% block content %}
<!--          Profile container          -->
<div class="container">
    <div class="row">
        <div class="col-12 col-md-10 col-lg-8 offset-md-1 offset-lg-2 mt-3 mb-3">

            <!--          Title and sub title          -->
            <hr>
            <h1 class="logo-font text-center font-weight-bold" style="font-size: 30px;">{{ profile.user.username }}'s
                profile</h1>
            <hr>
        </div>
    </div>
    <div class="row">
        <div class="card col-12 col-md-10 col-lg-8 offset-md-1 offset-lg-2 mt-3 mb-3">
            <div class="row mx-0">
                <div class="col-12 col-md-10 offset-md-1 mt-3 mb-3">
                    {% if profile.image %}
                    <div class="row justify-content-center mt-2 mt-md-3 mb-5">
                        <div class="profile-image-card">
                            <img class="profile-image img-fluid" src="{{ profile.image.url }}"
                                alt="Profile picture of {{ profile.user.username }}">
                        </div>
                    </div>
                    {% endif %}
                    {% if profile.bio %}
                    <div class="row justify-content-center mb-5">
                        <div class="col-12 col-md-8">
                            <p class="mb-0">{{ profile.bio }}</p>
                        </div>
                    </div>
                    {% endif %}
                    {% if profile.get_fav_brand_display %}
                    <div class="row">
                        <div class="col-12 col-md-6">
                            <p class="mb-0 text-black font-weight-bold">Favourite Brand:</p>
                        </div>
                        <div class="col-12 col-md-6 text-md-right">
                            <p class="mb-0">{{ profile.get_fav_brand_display }}</p>
                        </div>
                    </div>
                    {% endif %}
                    {% if profile.get_fav_os_display %}
                    <div class="row">
                        <div class="col-12 col-md-6">
                            <p class="mb-0 text-black font-weight-bold">Favourite Operating System:</p>
                        </div>
                        <div class="col-12 col-md-6 text-md-right">
                            <p class="mb-0">{{ profile.get_fav_os_display }}</p>
                        </div>
                    </div>
                    {% endif %}
                    {% if request.user == profile.user %}

                    <!--          Personal Information          -->
                    <hr>
                    <h2 class="logo-font text-center" style="font-size: 20px;">Personal Information</h2>
                    <hr>
                    {% if profile.default_phone_number %}
                    <div class="row">
                        <div class="col-12 col-md-4">
                            <p class="mb-0 text-black font-weight-bold">Phone Number:</p>
                        </div>
                        <div class="col-12 col-md-8 text-md-right">
                            <p class="mb-0">{{ profile.default_phone_number }}</p>
                        </div>
                    </div>
                    {% endif %}
                    {% if profile.default_street_address1 %}
                    <div class="row">
                        <div class="col-12 col-md-4">
                            <p class="mb-0 text-black font-weight-bold">Street Address:</p>
                        </div>
                        <div class="col-12 col-md-8 text-md-right">
                            <p class="mb-0">{{ profile.default_street_address1 }}</p>
                        </div>
                    </div>
                    {% endif %}
                    {% if profile.default_street_address2 %}
                    <div class="row">
                        <div class="col-12 col-md-4">
                            <p class="mb-0 text-black font-weight-bold">Street Address 2:</p>
                        </div>
                        <div class="col-12 col-md-8 text-md-right">
                            <p class="mb-0">{{ profile.default_street_addres2 }}</p>
                        </div>
                    </div>
                    {% endif %}
                    {% if profile.default_town_or_city %}
                    <div class="row">
                        <div class="col-12 col-md-4">
                            <p class="mb-0 text-black font-weight-bold">Town or City:</p>
                        </div>
                        <div class="col-12 col-md-8 text-md-right">
                            <p class="mb-0">{{ profile.default_town_or_city }}</p>
                        </div>
                    </div>
                    {% endif %}
                    {% if profile.default_county %}
                    <div class="row">
                        <div class="col-12 col-md-4">
                            <p class="mb-0 text-black font-weight-bold">County:</p>
                        </div>
                        <div class="col-12 col-md-8 text-md-right">
                            <p class="mb-0">{{ profile.default_county }}</p>
                        </div>
                    </div>
                    {% endif %}
                    {% if profile.default_postcode %}
                    <div class="row">
                        <div class="col-12 col-md-4">
                            <p class="mb-0 text-black font-weight-bold">Postal Code:</p>
                        </div>
                        <div class="col-12 col-md-8 text-md-right">
                            <p class="mb-0">{{ profile.default_postcode }}</p>
                        </div>
                    </div>
                    {% endif %}
                    {% if profile.get_default_country_display %}
                    <div class="row">
                        <div class="col-12 col-md-4">
                            <p class="mb-0 text-black font-weight-bold">Country:</p>
                        </div>
                        <div class="col-12 col-md-8 text-md-right">
                            <p class="mb-0">{{ profile.get_default_country_display }}</p>
                        </div>
                    </div>
                    {% endif %}

                    <!--          Edit/Delete account          -->
                    <hr>
                    <h2 class="logo-font text-center" style="font-size: 20px;">Danger</h2>
                    <hr>
                    <div class="col">
                        <div class="d-flex justify-content-center">
                            <small class="text-center mt-1">
                                <a class="btn main-button font-weight-bold rounded mx-3 mb-3 mx-lg-5"
                                    href="{% url 'edit_profile' %}">Edit</a>
                                <a class="btn btn-outline-danger font-weight-bold rounded mx-3 mb-3 mx-lg-5"
                                    href="{% url 'delete_account' %}">Delete</a>
                            </small>
                        </div>
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

profiles/templates/profiles/purchases.html
{% extends "base.html" %}
{% load static %}

{% block head_title %}- Purchases{% endblock %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/profile.css' %}">
{% endblock %}

{% block page_header %}
<div class="container header-container">
    <div class="row">
        <div class="col"></div>
    </div>
</div>
{% endblock %}

{% block content %}
<!--          Purchases container          -->
<div class="container">
    <div class="row">
        <div class="col-12 col-md-10 col-lg-8 offset-md-1 offset-lg-2 mt-3 mb-3">

            <!--          Title and sub title          -->
            <hr>
            <h1 class="logo-font text-center font-weight-bold" style="font-size: 30px;">Purchases</h1>
            <hr>
        </div>
    </div>
    <div class="row">
        <div class="card col-12 col-md-10 col-lg-8 offset-md-1 offset-lg-2 mt-3 mb-3">
            <div class="row mx-0">
                <div class="col-12 mt-3 mb-3">
                    <h2 class="mb-3 font-weight-bold" style="font-size: 20px;">Purchases history</h2>

                    <!--          Loop through the orders          -->
                    {% if orders %}

                    <!--          Medium screens and up          -->
                    <div class="purchases-history table-responsive d-none d-md-block">
                        <table class="table table-sm table-borderless">
                            <thead>
                                <tr>
                                    <th>Order Number</th>
                                    <th>Date</th>
                                    <th>Items</th>
                                    <th>Order Total</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for order in orders %}
                                <tr>
                                    <td>
                                        <a class="font-weight-bold text-muted"
                                            href="{% url 'purchases_history' order.order_number %}"
                                            title="{{ order.order_number }}">
                                            {{ order.order_number|truncatechars:8 }}
                                        </a>
                                    </td>
                                    <td>{{ order.date }}</td>
                                    <td>
                                        <ul class="list-unstyled">
                                            {% for item in order.lineitems.all %}
                                            <li class="small">
                                                {{ item.product.name }} x{{ item.quantity }}
                                            </li>
                                            {% endfor %}
                                        </ul>
                                    </td>
                                    <td>€{{ order.grand_total }}</td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>

                    <!--          Small screens          -->
                    <div class="d-block d-md-none pt-2">
                        {% for order in orders %}
                        <p><strong>Order Number: </strong><a class="font-weight-bold text-muted"
                                href="{% url 'purchases_history' order.order_number %}"
                                title="{{ order.order_number }}">
                                {{ order.order_number|truncatechars:8 }}
                            </a></p>
                        <p><strong>Date: </strong>{{ order.date }}</p>
                        <p><strong>Items: </strong></p>
                        <ul class="list-unstyled">
                            {% for item in order.lineitems.all %}
                            <li class="small">
                                {{ item.product.name }} x{{ item.quantity }}
                            </li>
                            {% endfor %}
                        </ul>
                        <p><Strong>Order Total: </Strong>€{{ order.grand_total }}</p>
                        <hr>
                        {% endfor %}
                    </div>
                    {% else %}
                    <p class="lead mb-5 text-center">You haven't done any purchase yet</p>
                    <div class="text-center">
                        <a href="{% url 'products' %}" class="btn main-button rounded btn-lg">
                            <span class="icon">
                                <i class="fas fa-chevron-left text-white fa-beat"></i>
                            </span>
                            <span> Keep Shopping</span>
                        </a>
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}